# nginx-values.yaml
controller:
  metrics:
    enabled: true
    service:
      enabled: true
      # We MUST name the port so our manual file can find it
      ports:
        metrics: 10254
      # We MUST add labels so our manual file can find it
      labels:
        app.kubernetes.io/component: "controller"
        app.kubernetes.io/instance: "ingress-nginx"
        app.kubernetes.io/name: "ingress-nginx"